/* shared day plan — single source of truth for index.html, admin.html and check.mjs. */
const DAY=[
 {t:"8:00",icon:"☀️",title:"Wake up — dress & make your bed",tz:"起床——穿衣、鋪床",kind:"routine",
  txt:{lucien:"Dress and shoes — a buddy helps",lili:"Dress, hair, make your bed",luis:"Open the windows — captain the morning"},
  txtz:{lucien:"穿衣穿鞋——夥伴幫忙",lili:"穿衣、梳頭、鋪床",luis:"開窗——當早晨的隊長"}},
 {t:"8:15",icon:"🥐",title:"Breakfast + kitchen job",tz:"早餐＋廚房工作",kind:"routine",
  txt:{lucien:"Carry your bowl, help set the table",lili:"Do your chore of the week",luis:"Do your chore of the week"},
  txtz:{lucien:"端碗、幫忙擺餐桌",lili:"做本週家事",luis:"做本週家事"}},
 {t:"8:45",icon:"🎯",title:"Skill block",tz:"技能時間",kind:"mission",pool:"skill"},
 {t:"9:30",icon:"📚",title:"Reading — quiet & comfy",tz:"閱讀——安靜舒服",kind:"routine",
  txt:{lucien:"Picture books, or listen to a story",lili:"Read a page aloud to someone",luis:"Chapter book — 20 quiet minutes"},
  txtz:{lucien:"看圖畫書或聽故事",lili:"大聲唸一頁給別人聽",luis:"章節書——安靜20分鐘"}},
 {t:"10:00",icon:"✏️",title:"Homework",tz:"暑假作業",kind:"mission",pool:"homework"},
 {t:"11:15",icon:"📱",title:"Screen #1 — 45 min, earned",tz:"螢幕#1——45分鐘（要先賺到）",kind:"routine",
  txt:{lucien:"Only if your morning boxes are ticked ✓",lili:"Only if skill + reading are ticked ✓",luis:"Only if skill + reading are ticked ✓ — set your own timer"},
  txtz:{lucien:"早上的格子打勾才可以 ✓",lili:"技能＋閱讀打勾才可以 ✓",luis:"技能＋閱讀打勾 ✓——自己設定時器"}},
 {t:"12:00",icon:"🍽",title:"Lunch + kitchen job",tz:"午餐＋廚房工作",kind:"routine",
  txt:{lucien:"Napkins, carry your plate",lili:"Chore of the week",luis:"Chore of the week"},
  txtz:{lucien:"餐巾、端自己的盤子",lili:"本週家事",luis:"本週家事"}},
 {t:"12:45",icon:"🤫",title:"Quiet hour — peak heat",tz:"安靜時間——最熱的時候",kind:"routine",
  txt:{lucien:"Nap time 😴",lili:"Rest or audiobook",luis:"Read or a quiet hobby"},
  txtz:{lucien:"午睡 😴",lili:"休息或聽有聲書",luis:"閱讀或安靜的嗜好"}},
 {t:"14:00",icon:"🧩",title:"Project time",tz:"專題時間",kind:"mission",pool:"project"},
 {t:"15:45",icon:"📱",title:"Screen #2 — 45 min, earned",tz:"螢幕#2——45分鐘（要先賺到）",kind:"routine",
  txt:{lucien:"Boxes ticked ✓ then videos or a game",lili:"Boxes ticked ✓ then Minecraft or a game",luis:"Boxes ticked ✓ then Minecraft or a game"},
  txtz:{lucien:"格子打勾✓再看影片或玩遊戲",lili:"格子打勾✓再玩Minecraft或遊戲",luis:"格子打勾✓再玩Minecraft或遊戲"}},
 {t:"16:30",icon:"🧠",title:"Free — invent your own game",tz:"自由——發明你自己的遊戲",kind:"mission",pool:"boredom"},
 {t:"17:15",icon:"⚽",title:"Sport & move (when it cools)",tz:"運動時間（涼快時）",kind:"mission",pool:"sport"},
 {t:"18:00",icon:"🧹",title:"Tidy patrol + house help",tz:"整理巡邏＋家事幫手",kind:"mission",pool:"house"},
 {t:"18:30",icon:"🍽",title:"Dinner + kitchen job",tz:"晚餐＋廚房工作",kind:"routine",
  txt:{lucien:"Carry your plate",lili:"Chore of the week",luis:"Chore + help cook"},
  txtz:{lucien:"端你的盤子",lili:"本週家事",luis:"家事＋幫忙煮飯"}},
 {t:"19:30",icon:"🌙",title:"Bath, family game, bed",tz:"洗澡、家庭遊戲、睡覺",kind:"routine",
  txt:{lucien:"Bed 20:30",lili:"Lights out 21:00",luis:"Lights out 21:15"},
  txtz:{lucien:"8點30分睡覺",lili:"9點熄燈",luis:"9點15分熄燈"}},
 {t:"✨",icon:"📸",title:"Bonus — photo mission of the day",tz:"加碼——今日照片任務",kind:"mission",pool:"photo"},
];
if(typeof window!=="undefined")window.SQ_DAY_DATA=DAY;
if(typeof module!=="undefined"&&module.exports)module.exports={DAY:DAY};
