/* shared day plan — single source of truth for index.html, admin.html and check.mjs.
   tips: ordered [en, zh] guide steps, shown on the current/next block to coach the kid. */
const DAY=[
 {t:"8:00",icon:"☀️",title:"Wake up — dress & make your bed",tz:"起床——穿衣、鋪床",kind:"routine",
  txt:{lucien:"Dress and shoes — a buddy helps",lili:"Dress, hair, make your bed",luis:"Open the windows — captain the morning"},
  txtz:{lucien:"穿衣穿鞋——夥伴幫忙",lili:"穿衣、梳頭、鋪床",luis:"開窗——當早晨的隊長"},
  tips:[["Open the curtains — sunshine in!","拉開窗簾——讓陽光進來！"],
        ["Clothes on, bed neat, pillow on top","穿好衣服、棉被鋪平、枕頭放好"],
        ["Wash your face and brush your teeth","洗臉、刷牙"]]},
 {t:"8:15",icon:"🥐",title:"Breakfast + kitchen job",tz:"早餐＋廚房工作",kind:"routine",
  txt:{lucien:"Carry your bowl, help set the table",lili:"Do your chore of the week",luis:"Do your chore of the week"},
  txtz:{lucien:"端碗、幫忙擺餐桌",lili:"做本週家事",luis:"做本週家事"},
  tips:[["Help set the table before eating","吃飯前先幫忙擺餐桌"],
        ["Sit down to eat, drink some water","坐好吃飯、喝點水"],
        ["Bring your dishes to the sink after","吃完把碗盤拿到水槽"]]},
 {t:"8:45",icon:"🎯",title:"Skill block",tz:"技能時間",kind:"mission",pool:"skill",
  tips:[["Read your mission first — what exactly to do?","先讀清楚任務——到底要做什麼？"],
        ["Get everything ready before you start","開始前先把東西準備好"],
        ["Done? Tick ✓ and tell someone what you learned","完成後打勾✓，告訴別人你學到什麼"]]},
 {t:"9:30",icon:"📚",title:"Reading — quiet & comfy",tz:"閱讀——安靜舒服",kind:"routine",
  txt:{lucien:"Picture books, or listen to a story",lili:"Read a page aloud to someone",luis:"Chapter book — 20 quiet minutes"},
  txtz:{lucien:"看圖畫書或聽故事",lili:"大聲唸一頁給別人聽",luis:"章節書——安靜20分鐘"},
  tips:[["Pick one book and a comfy spot","選一本書、找個舒服的位置"],
        ["Read quietly the whole time — no jumping around","整段時間安靜閱讀——不要跑來跑去"],
        ["Share your favorite part with someone after","讀完跟別人分享你最喜歡的部分"]]},
 {t:"10:00",icon:"✏️",title:"Homework",tz:"暑假作業",kind:"mission",pool:"homework",
  tips:[["Clear the table, pencil and eraser ready","桌面清空、鉛筆橡皮擦準備好"],
        ["Write slowly and neatly — quality first!","慢慢寫、寫整齊——品質第一！"],
        ["Show Papa or Maman when you finish","完成後給爸爸或媽媽看"]]},
 {t:"11:15",icon:"📱",title:"Screen #1 — 45 min, earned",tz:"螢幕#1——45分鐘（要先賺到）",kind:"routine",
  txt:{lucien:"Only if your morning boxes are ticked ✓",lili:"Only if skill + reading are ticked ✓",luis:"Only if skill + reading are ticked ✓ — set your own timer"},
  txtz:{lucien:"早上的格子打勾才可以 ✓",lili:"技能＋閱讀打勾才可以 ✓",luis:"技能＋閱讀打勾 ✓——自己設定時器"},
  tips:[["First check: are your morning boxes ticked ✓?","先檢查：早上的格子都打勾了嗎✓？"],
        ["Set the 45-minute timer BEFORE you start","開始前先設好45分鐘計時器"],
        ["Timer rings = screen off, no extra time","計時器響了就關螢幕，不加時間"]]},
 {t:"12:00",icon:"🍽",title:"Lunch + kitchen job",tz:"午餐＋廚房工作",kind:"routine",
  txt:{lucien:"Napkins, carry your plate",lili:"Chore of the week",luis:"Chore of the week"},
  txtz:{lucien:"餐巾、端自己的盤子",lili:"本週家事",luis:"本週家事"},
  tips:[["Wash hands, then help set the table","先洗手，再幫忙擺餐桌"],
        ["Eat your veggies too","青菜也要吃"],
        ["Plate to the sink, wipe your spot","盤子拿到水槽、擦好桌面"]]},
 {t:"12:45",icon:"🤫",title:"Quiet hour — peak heat",tz:"安靜時間——最熱的時候",kind:"routine",
  txt:{lucien:"Nap time 😴",lili:"Rest or audiobook",luis:"Read or a quiet hobby"},
  txtz:{lucien:"午睡 😴",lili:"休息或聽有聲書",luis:"閱讀或安靜的嗜好"},
  tips:[["Choose ONE quiet thing before you start","開始前先選好一件安靜的事"],
        ["Stay in your spot — whisper voices only","待在自己的位置——只能小小聲"],
        ["Let everyone else rest too","也讓別人好好休息"]]},
 {t:"14:00",icon:"🧩",title:"Project time",tz:"專題時間",kind:"mission",pool:"project",
  tips:[["Plan first: what will you make today?","先計畫：今天要做什麼？"],
        ["Gather your materials and protect the table","準備好材料、保護桌面"],
        ["Cleaning up is part of the project!","收拾也是專題的一部分！"]]},
 {t:"15:45",icon:"📱",title:"Screen #2 — 45 min, earned",tz:"螢幕#2——45分鐘（要先賺到）",kind:"routine",
  txt:{lucien:"Boxes ticked ✓ then videos or a game",lili:"Boxes ticked ✓ then Minecraft or a game",luis:"Boxes ticked ✓ then Minecraft or a game"},
  txtz:{lucien:"格子打勾✓再看影片或玩遊戲",lili:"格子打勾✓再玩Minecraft或遊戲",luis:"格子打勾✓再玩Minecraft或遊戲"},
  tips:[["First check: are your boxes ticked ✓?","先檢查：格子都打勾了嗎✓？"],
        ["Set the 45-minute timer BEFORE you start","開始前先設好45分鐘計時器"],
        ["Timer rings = screen off, no extra time","計時器響了就關螢幕，不加時間"]]},
 {t:"16:30",icon:"🧠",title:"Free — invent your own game",tz:"自由——發明你自己的遊戲",kind:"mission",pool:"boredom",
  tips:[["No screens — invent with what you have","不用螢幕——用手邊的東西發明"],
        ["Bored? That's where great ideas start!","無聊嗎？好點子就是這樣開始的！"],
        ["Show your invention to someone","把你的發明展示給別人看"]]},
 {t:"17:15",icon:"⚽",title:"Sport & move (when it cools)",tz:"運動時間（涼快時）",kind:"mission",pool:"sport",
  tips:[["Water bottle and shoes first","先拿水壺、穿好鞋子"],
        ["Warm up, then move until you're puffed","先熱身，再動到會喘"],
        ["Drink water when you finish","結束後記得喝水"]]},
 {t:"18:00",icon:"🧹",title:"Tidy patrol + house help",tz:"整理巡邏＋家事幫手",kind:"mission",pool:"house",
  tips:[["Check your mission zone first","先看看你的任務區域"],
        ["Every thing goes back to its home","每樣東西都放回它的家"],
        ["Ask: what else can I help with?","問問：還有什麼可以幫忙的？"]]},
 {t:"18:30",icon:"🍽",title:"Dinner + kitchen job",tz:"晚餐＋廚房工作",kind:"routine",
  txt:{lucien:"Carry your plate",lili:"Chore of the week",luis:"Chore + help cook"},
  txtz:{lucien:"端你的盤子",lili:"本週家事",luis:"家事＋幫忙煮飯"},
  tips:[["Wash hands, help carry the food","洗手、幫忙端菜"],
        ["Tell one good thing about your day","說一件今天發生的好事"],
        ["Dishes to the sink after eating","吃完把碗盤拿到水槽"]]},
 {t:"19:30",icon:"🌙",title:"Bath, family game, bed",tz:"洗澡、家庭遊戲、睡覺",kind:"routine",
  txt:{lucien:"Bed 20:30",lili:"Lights out 21:00",luis:"Lights out 21:15"},
  txtz:{lucien:"8點30分睡覺",lili:"9點熄燈",luis:"9點15分熄燈"},
  tips:[["Bath, pajamas, brush your teeth","洗澡、穿睡衣、刷牙"],
        ["One family game or one story","一個家庭遊戲或一個故事"],
        ["Lights out at YOUR time — sweet dreams!","時間到就熄燈——祝好夢！"]]},
 {t:"✨",icon:"📸",title:"Bonus — photo mission of the day",tz:"加碼——今日照片任務",kind:"mission",pool:"photo",
  tips:[["Read today's photo mission carefully","仔細讀今天的照片任務"],
        ["Set up your very best shot","好好構圖，拍出最棒的一張"],
        ["Upload it with the 📸 button as proof","用📸按鈕上傳當作證明"]]},
];
if(typeof window!=="undefined")window.SQ_DAY_DATA=DAY;
if(typeof module!=="undefined"&&module.exports)module.exports={DAY:DAY};
