# Pack native Brain Gym sprites into per-scene atlases and emit sprites/manifest.json.
#
#   powershell -File scripts/pack-atlas.ps1
#
# Reads assets/brain/sprites/src/atlas-spec.json. Rows are objects, columns are
# state/frames, every cell is the same size, and cells are separated by `padding`
# transparent native pixels. Sprites smaller than the cell sit at the cell's top-left
# so a manifest entry is the sprite's own native box, never the padded cell.
#
# Nothing is trimmed or rescaled: the packer only copies pixels, so animation
# registration established by pixelize.ps1 survives packing.

param(
  [string]$Root = (Join-Path $PSScriptRoot ".." )
)

Add-Type -AssemblyName System.Drawing

$root    = (Resolve-Path $Root).Path
$srcDir  = Join-Path $root "assets\brain\sprites\src"
$outDir  = Join-Path $root "assets\brain\sprites"
$spec    = Get-Content (Join-Path $srcDir "atlas-spec.json") -Raw | ConvertFrom-Json

$cell = [int]$spec.cell
$pad  = [int]$spec.padding
$manifest = [ordered]@{}

foreach ($atlas in $spec.atlases) {
  $rows = @($atlas.sprites).Count
  $cols = 1
  foreach ($s in $atlas.sprites) { if ([int]$s.frames -gt $cols) { $cols = [int]$s.frames } }

  $w = $cols * $cell + ($cols - 1) * $pad
  $h = $rows * $cell + ($rows - 1) * $pad
  $bmp = New-Object System.Drawing.Bitmap $w, $h, ([System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
  $g = [System.Drawing.Graphics]::FromImage($bmp)
  $g.CompositingMode = 'SourceCopy'      # copy alpha verbatim, never blend
  $g.InterpolationMode = 'NearestNeighbor'
  $g.PixelOffsetMode = 'Half'

  $entries = [ordered]@{}
  $r = 0
  foreach ($s in $atlas.sprites) {
    $img = [System.Drawing.Bitmap]::FromFile((Join-Path $srcDir $s.src))
    $native = [int]$s.native
    $frames = [int]$s.frames
    if ($img.Width -ne ($native * $frames) -or $img.Height -ne $native) {
      throw "$($s.src): expected $($native * $frames)x$native for $frames frame(s), got $($img.Width)x$($img.Height)"
    }
    $y = $r * ($cell + $pad)
    for ($f = 0; $f -lt $frames; $f++) {
      $x = $f * ($cell + $pad)
      $g.DrawImage($img,
        (New-Object System.Drawing.Rectangle $x, $y, $native, $native),
        (New-Object System.Drawing.Rectangle ($f * $native), 0, $native, $native),
        [System.Drawing.GraphicsUnit]::Pixel)
    }
    $img.Dispose()

    $entry = [ordered]@{
      x           = 0
      y           = $y
      w           = $native
      h           = $native
      frames      = $frames
      step        = $cell + $pad     # x advance between frames
      anchor      = $s.anchor
      scene       = $atlas.scene
      ramp        = $s.ramp
      provenance  = $s.provenance
      use         = $s.use
    }
    # Optional, passed straight through: `values` maps frame index to denomination,
    # `content` is the opaque box inside the padded native square, and `regions` are
    # named native-pixel areas the scene lays DOM controls over (drawer wells, display).
    foreach ($extra in @("values","content","regions")) {
      if ($s.PSObject.Properties[$extra]) { $entry[$extra] = $s.$extra }
    }
    $entries[$s.id] = $entry
    $r++
  }

  $g.Dispose()
  $file = Join-Path $outDir $atlas.file
  $bmp.Save($file, [System.Drawing.Imaging.ImageFormat]::Png)
  $bmp.Dispose()

  $manifest[$atlas.file] = [ordered]@{
    scene   = $atlas.scene
    width   = $w
    height  = $h
    cell    = $cell
    padding = $pad
    sprites = $entries
  }
  "{0}  {1}x{2}  {3} KB  {4} sprites" -f $atlas.file, $w, $h,
    [Math]::Round((Get-Item $file).Length / 1KB, 1), @($atlas.sprites).Count
}

$json = [ordered]@{
  note    = "Generated by scripts/pack-atlas.ps1 from assets/brain/sprites/src/atlas-spec.json. Do not hand-edit."
  atlases = $manifest
} | ConvertTo-Json -Depth 8
# WriteAllText with an explicit no-BOM encoding: PowerShell 5.1's -Encoding utf8 emits a
# BOM, and JSON.parse rejects it.
[System.IO.File]::WriteAllText((Join-Path $outDir "manifest.json"), $json,
  (New-Object System.Text.UTF8Encoding $false))
"manifest.json written"
