import type { ReadingLevel } from "../../../core/src/interaction-profile.js";
import type { LearnerProfile, LearningDomain, MathQuestion, VocabularyExercise, VocabularyMode } from "../types.js";
import { classifyGranularLanguageSkill, vocabularyModeForLanguageSkill } from "./LanguageSkillRules.js";

export const CURRICULUM_SKILL_IDS = [
  "math.number_comparison.within_20",
  "math.addition.within_5",
  "math.number_bonds.to_10",
  "math.addition.within_20",
  "math.subtraction.within_20",
  "math.number_comparison.within_100",
  "math.number_bonds.to_20",
  "math.addition.within_100",
  "math.subtraction.within_100",
  "math.multiplication.tables_2_5_10",
  "math.multiplication.tables_2_to_9",
  "math.addition.within_200",
  "language.initial_sound",
  "language.word_build.simple",
  "language.picture_vocabulary.basic",
  "language.high_frequency.recall",
  "language.spelling_patterns.basic",
  "language.word_translation.basic",
  "language.sentence_patterns.simple",
  "language.sentence_patterns.questions",
  "language.bopomofo.sound_symbol",
  "language.bopomofo.word_build",
  "science.animals.groups",
  "science.plants.parts",
  "science.body.organ_jobs",
  "science.matter.states",
  "science.weather.water_cycle",
  "science.space.earth_moon_sun",
  "geography.map.cardinal_directions",
  "geography.map.symbols",
  "geography.land_water.features",
  "geography.world.continents_oceans",
  "geography.world.equator_hemispheres",
  "geography.environment.climate_clues",
  "history.time.past_present",
  "history.time.before_after",
  "history.sources.clues",
  "history.ancient.egypt_clues",
  "history.ancient.china_clues",
  "history.change.communication",
  // Legacy coarse IDs remain readable so old telemetry/session records do not become invalid.
  "language.word_copy",
  "language.word_recall",
  "language.word_translation",
  "language.sentence_recall",
  "language.bopomofo",
] as const;

export type CurriculumSkillId = typeof CURRICULUM_SKILL_IDS[number];
export type CurriculumSkillReadiness = "ready" | "locked";

export interface CurriculumSkillDefinition {
  id: CurriculumSkillId;
  domain: Extract<LearningDomain, "math" | "language" | "science" | "geography" | "history">;
  strand: string;
  label: string;
  labelZh: string;
  shortLabel: string;
  shortLabelZh: string;
  icon: string;
  minAge: number;
  maxAge?: number;
  readingLevels?: ReadingLevel[];
  prerequisites: CurriculumSkillId[];
  prerequisiteBypassAge?: number;
  introductionNeed: number;
  directorEligible: boolean;
  launch:
    | { gameId: "calc"; mathSkill: CurriculumSkillId }
    | { gameId: "vocab"; vocabularyMode: VocabularyMode }
    | { gameId: "science"; lessonId: string }
    | { gameId: "geography"; lessonId: string }
    | { gameId: "history"; lessonId: string };
}

const SKILLS: readonly CurriculumSkillDefinition[] = [
  {
    id: "math.number_comparison.within_20",
    domain: "math",
    strand: "number_sense",
    label: "Compare numbers to 20",
    labelZh: "20 以內比大小",
    shortLabel: "Compare to 20",
    shortLabelZh: "比到 20",
    icon: "⚖️",
    minAge: 4,
    maxAge: 7,
    prerequisites: [],
    introductionNeed: 0.7,
    directorEligible: true,
    launch: { gameId: "calc", mathSkill: "math.number_comparison.within_20" },
  },
  {
    id: "math.addition.within_5",
    domain: "math",
    strand: "number_operations",
    label: "Addition to 5",
    labelZh: "5 以內加法",
    shortLabel: "+ to 5",
    shortLabelZh: "加到 5",
    icon: "➕",
    minAge: 3,
    maxAge: 6,
    prerequisites: [],
    introductionNeed: 0.78,
    directorEligible: true,
    launch: { gameId: "calc", mathSkill: "math.addition.within_5" },
  },
  {
    id: "math.number_bonds.to_10",
    domain: "math",
    strand: "number_bonds",
    label: "Number bonds to 10",
    labelZh: "10 以內數字分合",
    shortLabel: "Bonds to 10",
    shortLabelZh: "分合到 10",
    icon: "🧩",
    minAge: 5,
    maxAge: 8,
    prerequisites: ["math.addition.within_5"],
    prerequisiteBypassAge: 6,
    introductionNeed: 0.75,
    directorEligible: true,
    launch: { gameId: "calc", mathSkill: "math.number_bonds.to_10" },
  },
  {
    id: "math.addition.within_20",
    domain: "math",
    strand: "number_operations",
    label: "Addition to 20",
    labelZh: "20 以內加法",
    shortLabel: "+ to 20",
    shortLabelZh: "加到 20",
    icon: "➕",
    minAge: 5,
    maxAge: 8,
    prerequisites: ["math.addition.within_5"],
    prerequisiteBypassAge: 6,
    introductionNeed: 0.78,
    directorEligible: true,
    launch: { gameId: "calc", mathSkill: "math.addition.within_20" },
  },
  {
    id: "math.subtraction.within_20",
    domain: "math",
    strand: "number_operations",
    label: "Subtraction to 20",
    labelZh: "20 以內減法",
    shortLabel: "− to 20",
    shortLabelZh: "減到 20",
    icon: "➖",
    minAge: 5,
    maxAge: 8,
    prerequisites: ["math.addition.within_5"],
    prerequisiteBypassAge: 6,
    introductionNeed: 0.76,
    directorEligible: true,
    launch: { gameId: "calc", mathSkill: "math.subtraction.within_20" },
  },
  {
    id: "math.number_comparison.within_100",
    domain: "math",
    strand: "number_sense",
    label: "Compare numbers to 100",
    labelZh: "100 以內比大小",
    shortLabel: "Compare to 100",
    shortLabelZh: "比到 100",
    icon: "⚖️",
    minAge: 6,
    maxAge: 9,
    prerequisites: ["math.number_comparison.within_20"],
    prerequisiteBypassAge: 7,
    introductionNeed: 0.68,
    directorEligible: true,
    launch: { gameId: "calc", mathSkill: "math.number_comparison.within_100" },
  },
  {
    id: "math.number_bonds.to_20",
    domain: "math",
    strand: "number_bonds",
    label: "Number bonds to 20",
    labelZh: "20 以內數字分合",
    shortLabel: "Bonds to 20",
    shortLabelZh: "分合到 20",
    icon: "🧩",
    minAge: 6,
    maxAge: 9,
    prerequisites: ["math.number_bonds.to_10", "math.addition.within_20"],
    prerequisiteBypassAge: 7,
    introductionNeed: 0.74,
    directorEligible: true,
    launch: { gameId: "calc", mathSkill: "math.number_bonds.to_20" },
  },
  {
    id: "math.addition.within_100",
    domain: "math",
    strand: "number_operations",
    label: "Addition to 100",
    labelZh: "100 以內加法",
    shortLabel: "+ to 100",
    shortLabelZh: "加到 100",
    icon: "➕",
    minAge: 7,
    maxAge: 10,
    prerequisites: ["math.addition.within_20"],
    prerequisiteBypassAge: 8,
    introductionNeed: 0.77,
    directorEligible: true,
    launch: { gameId: "calc", mathSkill: "math.addition.within_100" },
  },
  {
    id: "math.subtraction.within_100",
    domain: "math",
    strand: "number_operations",
    label: "Subtraction to 100",
    labelZh: "100 以內減法",
    shortLabel: "− to 100",
    shortLabelZh: "減到 100",
    icon: "➖",
    minAge: 7,
    maxAge: 10,
    prerequisites: ["math.subtraction.within_20"],
    prerequisiteBypassAge: 8,
    introductionNeed: 0.78,
    directorEligible: true,
    launch: { gameId: "calc", mathSkill: "math.subtraction.within_100" },
  },
  {
    id: "math.multiplication.tables_2_5_10",
    domain: "math",
    strand: "multiplication",
    label: "Times tables 2, 5 and 10",
    labelZh: "2、5、10 乘法表",
    shortLabel: "× 2, 5, 10",
    shortLabelZh: "乘 2、5、10",
    icon: "✖️",
    minAge: 7,
    maxAge: 10,
    prerequisites: ["math.addition.within_20"],
    prerequisiteBypassAge: 8,
    introductionNeed: 0.76,
    directorEligible: true,
    launch: { gameId: "calc", mathSkill: "math.multiplication.tables_2_5_10" },
  },
  {
    id: "math.multiplication.tables_2_to_9",
    domain: "math",
    strand: "multiplication",
    label: "Times tables 2 to 9",
    labelZh: "2 到 9 乘法表",
    shortLabel: "× 2–9",
    shortLabelZh: "乘 2–9",
    icon: "✖️",
    minAge: 8,
    maxAge: 12,
    prerequisites: ["math.multiplication.tables_2_5_10"],
    prerequisiteBypassAge: 9,
    introductionNeed: 0.78,
    directorEligible: true,
    launch: { gameId: "calc", mathSkill: "math.multiplication.tables_2_to_9" },
  },
  {
    id: "math.addition.within_200",
    domain: "math",
    strand: "number_operations",
    label: "Addition to 200",
    labelZh: "200 以內加法",
    shortLabel: "+ to 200",
    shortLabelZh: "加到 200",
    icon: "➕",
    minAge: 10,
    prerequisites: ["math.addition.within_100"],
    prerequisiteBypassAge: 11,
    introductionNeed: 0.72,
    directorEligible: true,
    launch: { gameId: "calc", mathSkill: "math.addition.within_200" },
  },
  {
    id: "language.initial_sound",
    domain: "language",
    strand: "phonics",
    label: "Initial letter and sound",
    labelZh: "首字母與發音",
    shortLabel: "Initial sound",
    shortLabelZh: "首音字母",
    icon: "🔤",
    minAge: 3,
    readingLevels: ["pre_reader", "early_reader"],
    prerequisites: [],
    introductionNeed: 0.82,
    directorEligible: true,
    launch: { gameId: "vocab", vocabularyMode: "copy" },
  },
  {
    id: "language.word_build.simple",
    domain: "language",
    strand: "word_building",
    label: "Build simple words",
    labelZh: "拼出簡單單字",
    shortLabel: "Build words",
    shortLabelZh: "拼簡單字",
    icon: "🧱",
    minAge: 4,
    readingLevels: ["pre_reader", "early_reader"],
    prerequisites: ["language.initial_sound"],
    prerequisiteBypassAge: 5,
    introductionNeed: 0.8,
    directorEligible: true,
    launch: { gameId: "vocab", vocabularyMode: "copy" },
  },
  {
    id: "language.picture_vocabulary.basic",
    domain: "language",
    strand: "vocabulary",
    label: "Picture vocabulary",
    labelZh: "看圖記單字",
    shortLabel: "Picture words",
    shortLabelZh: "看圖單字",
    icon: "🖼️",
    minAge: 5,
    readingLevels: ["early_reader", "reader"],
    prerequisites: ["language.word_build.simple"],
    prerequisiteBypassAge: 6,
    introductionNeed: 0.8,
    directorEligible: true,
    launch: { gameId: "vocab", vocabularyMode: "recall" },
  },
  {
    id: "language.high_frequency.recall",
    domain: "language",
    strand: "fluency",
    label: "Everyday word recall",
    labelZh: "常用單字回想",
    shortLabel: "Everyday words",
    shortLabelZh: "常用單字",
    icon: "⚡",
    minAge: 6,
    readingLevels: ["early_reader", "reader"],
    prerequisites: ["language.picture_vocabulary.basic"],
    prerequisiteBypassAge: 7,
    introductionNeed: 0.79,
    directorEligible: true,
    launch: { gameId: "vocab", vocabularyMode: "recall" },
  },
  {
    id: "language.spelling_patterns.basic",
    domain: "language",
    strand: "spelling",
    label: "Common spelling patterns",
    labelZh: "常見拼字規律",
    shortLabel: "Spelling patterns",
    shortLabelZh: "拼字規律",
    icon: "🧩",
    minAge: 7,
    readingLevels: ["early_reader", "reader"],
    prerequisites: ["language.high_frequency.recall"],
    prerequisiteBypassAge: 8,
    introductionNeed: 0.77,
    directorEligible: true,
    launch: { gameId: "vocab", vocabularyMode: "recall" },
  },
  {
    id: "language.word_translation.basic",
    domain: "language",
    strand: "meaning",
    label: "Link word meanings",
    labelZh: "連結單字意思",
    shortLabel: "Meaning links",
    shortLabelZh: "意思連結",
    icon: "🌐",
    minAge: 8,
    readingLevels: ["reader"],
    prerequisites: ["language.picture_vocabulary.basic"],
    prerequisiteBypassAge: 9,
    introductionNeed: 0.75,
    directorEligible: true,
    launch: { gameId: "vocab", vocabularyMode: "translate" },
  },
  {
    id: "language.sentence_patterns.simple",
    domain: "language",
    strand: "sentence_language",
    label: "Simple sentence patterns",
    labelZh: "簡單句型",
    shortLabel: "Sentence patterns",
    shortLabelZh: "簡單句型",
    icon: "💬",
    minAge: 7,
    readingLevels: ["early_reader", "reader"],
    prerequisites: ["language.high_frequency.recall"],
    prerequisiteBypassAge: 8,
    introductionNeed: 0.74,
    directorEligible: true,
    launch: { gameId: "vocab", vocabularyMode: "sentences" },
  },
  {
    id: "language.sentence_patterns.questions",
    domain: "language",
    strand: "sentence_language",
    label: "Everyday question patterns",
    labelZh: "常用問句句型",
    shortLabel: "Everyday questions",
    shortLabelZh: "常用問句",
    icon: "❓",
    minAge: 9,
    readingLevels: ["reader"],
    prerequisites: ["language.sentence_patterns.simple"],
    prerequisiteBypassAge: 10,
    introductionNeed: 0.7,
    directorEligible: true,
    launch: { gameId: "vocab", vocabularyMode: "sentences" },
  },
  {
    id: "language.bopomofo.sound_symbol",
    domain: "language",
    strand: "phonics",
    label: "Bopomofo sound-symbol match",
    labelZh: "注音聲符對應",
    shortLabel: "Zhuyin sounds",
    shortLabelZh: "注音聲符",
    icon: "ㄅ",
    minAge: 4,
    readingLevels: ["pre_reader", "early_reader", "reader"],
    prerequisites: [],
    introductionNeed: 0.82,
    directorEligible: true,
    launch: { gameId: "vocab", vocabularyMode: "bopomofo" },
  },
  {
    id: "language.bopomofo.word_build",
    domain: "language",
    strand: "phonics",
    label: "Build words with Bopomofo",
    labelZh: "用注音拼詞",
    shortLabel: "Zhuyin words",
    shortLabelZh: "注音拼詞",
    icon: "ㄅ",
    minAge: 5,
    readingLevels: ["early_reader", "reader"],
    prerequisites: ["language.bopomofo.sound_symbol"],
    prerequisiteBypassAge: 6,
    introductionNeed: 0.78,
    directorEligible: true,
    launch: { gameId: "vocab", vocabularyMode: "bopomofo" },
  },
  {
    id: "science.animals.groups",
    domain: "science",
    strand: "living_things",
    label: "Animal groups",
    labelZh: "動物族群",
    shortLabel: "Animal groups",
    shortLabelZh: "動物族群",
    icon: "🐾",
    minAge: 3,
    prerequisites: [],
    introductionNeed: 0.58,
    directorEligible: true,
    launch: { gameId: "science", lessonId: "science-animals-groups" },
  },
  {
    id: "science.plants.parts",
    domain: "science",
    strand: "living_things",
    label: "Plant parts and jobs",
    labelZh: "植物部位與工作",
    shortLabel: "Plant parts",
    shortLabelZh: "植物部位",
    icon: "🌱",
    minAge: 3,
    prerequisites: [],
    introductionNeed: 0.58,
    directorEligible: true,
    launch: { gameId: "science", lessonId: "science-plants-parts" },
  },
  {
    id: "science.body.organ_jobs",
    domain: "science",
    strand: "body",
    label: "Heart, lungs and brain",
    labelZh: "心臟、肺與大腦",
    shortLabel: "Body team",
    shortLabelZh: "身體小隊",
    icon: "🫀",
    minAge: 4,
    prerequisites: [],
    introductionNeed: 0.6,
    directorEligible: true,
    launch: { gameId: "science", lessonId: "science-body-jobs" },
  },
  {
    id: "science.matter.states",
    domain: "science",
    strand: "matter",
    label: "States of matter",
    labelZh: "物質的狀態",
    shortLabel: "Solid, liquid, gas",
    shortLabelZh: "固液氣",
    icon: "🧊",
    minAge: 4,
    prerequisites: [],
    introductionNeed: 0.62,
    directorEligible: true,
    launch: { gameId: "science", lessonId: "science-matter-states" },
  },
  {
    id: "science.weather.water_cycle",
    domain: "science",
    strand: "earth_science",
    label: "Water cycle",
    labelZh: "水循環",
    shortLabel: "Water cycle",
    shortLabelZh: "水循環",
    icon: "🌦️",
    minAge: 4,
    prerequisites: [],
    introductionNeed: 0.64,
    directorEligible: true,
    launch: { gameId: "science", lessonId: "science-weather-water-cycle" },
  },
  {
    id: "science.space.earth_moon_sun",
    domain: "science",
    strand: "space",
    label: "Earth, Moon and Sun",
    labelZh: "地球、月球與太陽",
    shortLabel: "Earth, Moon, Sun",
    shortLabelZh: "地月日",
    icon: "🌍",
    minAge: 4,
    prerequisites: [],
    introductionNeed: 0.64,
    directorEligible: true,
    launch: { gameId: "science", lessonId: "science-space-motion" },
  },
  {
    id: "geography.map.cardinal_directions",
    domain: "geography",
    strand: "map_skills",
    label: "Compass directions",
    labelZh: "指南針方向",
    shortLabel: "North, east, south, west",
    shortLabelZh: "北東南西",
    icon: "🧭",
    minAge: 3,
    prerequisites: [],
    introductionNeed: 0.58,
    directorEligible: true,
    launch: { gameId: "geography", lessonId: "geography-cardinal-directions" },
  },
  {
    id: "geography.map.symbols",
    domain: "geography",
    strand: "map_skills",
    label: "Map symbols and keys",
    labelZh: "地圖符號與圖例",
    shortLabel: "Map symbols",
    shortLabelZh: "地圖符號",
    icon: "🗺️",
    minAge: 3,
    prerequisites: [],
    introductionNeed: 0.58,
    directorEligible: true,
    launch: { gameId: "geography", lessonId: "geography-map-symbols" },
  },
  {
    id: "geography.land_water.features",
    domain: "geography",
    strand: "physical_geography",
    label: "Land and water features",
    labelZh: "陸地與水域特徵",
    shortLabel: "Land and water",
    shortLabelZh: "陸地與水域",
    icon: "🏝️",
    minAge: 3,
    prerequisites: [],
    introductionNeed: 0.6,
    directorEligible: true,
    launch: { gameId: "geography", lessonId: "geography-land-water-features" },
  },
  {
    id: "geography.world.continents_oceans",
    domain: "geography",
    strand: "world",
    label: "Continents and oceans",
    labelZh: "大洲與海洋",
    shortLabel: "Continents & oceans",
    shortLabelZh: "大洲與海洋",
    icon: "🌍",
    minAge: 5,
    prerequisites: [],
    introductionNeed: 0.62,
    directorEligible: true,
    launch: { gameId: "geography", lessonId: "geography-continents-oceans" },
  },
  {
    id: "geography.world.equator_hemispheres",
    domain: "geography",
    strand: "world",
    label: "Equator and hemispheres",
    labelZh: "赤道與半球",
    shortLabel: "Equator & hemispheres",
    shortLabelZh: "赤道與半球",
    icon: "🌐",
    minAge: 6,
    prerequisites: [],
    introductionNeed: 0.64,
    directorEligible: true,
    launch: { gameId: "geography", lessonId: "geography-equator-hemispheres" },
  },
  {
    id: "geography.environment.climate_clues",
    domain: "geography",
    strand: "environment",
    label: "Environment and climate clues",
    labelZh: "環境與氣候線索",
    shortLabel: "Environment clues",
    shortLabelZh: "環境線索",
    icon: "🌦️",
    minAge: 5,
    prerequisites: [],
    introductionNeed: 0.64,
    directorEligible: true,
    launch: { gameId: "geography", lessonId: "geography-environment-clues" },
  },
  {
    id: "history.time.past_present",
    domain: "history",
    strand: "time",
    label: "Past and present",
    labelZh: "過去和現在",
    shortLabel: "Past & present",
    shortLabelZh: "過去和現在",
    icon: "🕰️",
    minAge: 3,
    prerequisites: [],
    introductionNeed: 0.58,
    directorEligible: true,
    launch: { gameId: "history", lessonId: "history-past-present" },
  },
  {
    id: "history.time.before_after",
    domain: "history",
    strand: "time",
    label: "Before and after",
    labelZh: "先和後",
    shortLabel: "Before & after",
    shortLabelZh: "先和後",
    icon: "⏳",
    minAge: 3,
    prerequisites: [],
    introductionNeed: 0.58,
    directorEligible: true,
    launch: { gameId: "history", lessonId: "history-before-after" },
  },
  {
    id: "history.sources.clues",
    domain: "history",
    strand: "sources",
    label: "History detectives",
    labelZh: "歷史偵探",
    shortLabel: "History clues",
    shortLabelZh: "歷史線索",
    icon: "🔎",
    minAge: 4,
    prerequisites: [],
    introductionNeed: 0.6,
    directorEligible: true,
    launch: { gameId: "history", lessonId: "history-clues-sources" },
  },
  {
    id: "history.ancient.egypt_clues",
    domain: "history",
    strand: "ancient_civilizations",
    label: "Ancient Egypt clues",
    labelZh: "古埃及線索",
    shortLabel: "Ancient Egypt",
    shortLabelZh: "古埃及",
    icon: "🏺",
    minAge: 5,
    prerequisites: [],
    introductionNeed: 0.64,
    directorEligible: true,
    launch: { gameId: "history", lessonId: "history-ancient-egypt" },
  },
  {
    id: "history.ancient.china_clues",
    domain: "history",
    strand: "ancient_civilizations",
    label: "Ancient China clues",
    labelZh: "古代中國線索",
    shortLabel: "Ancient China",
    shortLabelZh: "古代中國",
    icon: "🏯",
    minAge: 5,
    prerequisites: [],
    introductionNeed: 0.64,
    directorEligible: true,
    launch: { gameId: "history", lessonId: "history-ancient-china" },
  },
  {
    id: "history.change.communication",
    domain: "history",
    strand: "change_over_time",
    label: "Messages through time",
    labelZh: "通訊方式的變化",
    shortLabel: "Messages through time",
    shortLabelZh: "通訊變化",
    icon: "✉️",
    minAge: 6,
    prerequisites: [],
    introductionNeed: 0.64,
    directorEligible: true,
    launch: { gameId: "history", lessonId: "history-communication-change" },
  },
  // v0.4.6 and earlier coarse skills remain as non-director aliases for old telemetry.
  {
    id: "language.word_copy",
    domain: "language",
    strand: "legacy",
    label: "Legacy word copy",
    labelZh: "舊版照拼單字",
    shortLabel: "Word copy",
    shortLabelZh: "照拼單字",
    icon: "✍️",
    minAge: 3,
    prerequisites: [],
    introductionNeed: 0,
    directorEligible: false,
    launch: { gameId: "vocab", vocabularyMode: "copy" },
  },
  {
    id: "language.word_recall",
    domain: "language",
    strand: "legacy",
    label: "Legacy word recall",
    labelZh: "舊版單字回想",
    shortLabel: "Word recall",
    shortLabelZh: "回想單字",
    icon: "🧠",
    minAge: 5,
    prerequisites: [],
    introductionNeed: 0,
    directorEligible: false,
    launch: { gameId: "vocab", vocabularyMode: "recall" },
  },
  {
    id: "language.word_translation",
    domain: "language",
    strand: "legacy",
    label: "Legacy word translation",
    labelZh: "舊版單字翻譯",
    shortLabel: "Translate",
    shortLabelZh: "翻譯單字",
    icon: "🌐",
    minAge: 8,
    prerequisites: [],
    introductionNeed: 0,
    directorEligible: false,
    launch: { gameId: "vocab", vocabularyMode: "translate" },
  },
  {
    id: "language.sentence_recall",
    domain: "language",
    strand: "legacy",
    label: "Legacy sentence recall",
    labelZh: "舊版句子回想",
    shortLabel: "Sentences",
    shortLabelZh: "句子回想",
    icon: "💬",
    minAge: 9,
    prerequisites: [],
    introductionNeed: 0,
    directorEligible: false,
    launch: { gameId: "vocab", vocabularyMode: "sentences" },
  },
  {
    id: "language.bopomofo",
    domain: "language",
    strand: "legacy",
    label: "Legacy Bopomofo typing",
    labelZh: "舊版注音輸入",
    shortLabel: "Bopomofo",
    shortLabelZh: "注音",
    icon: "ㄅ",
    minAge: 5,
    prerequisites: [],
    introductionNeed: 0,
    directorEligible: false,
    launch: { gameId: "vocab", vocabularyMode: "bopomofo" },
  },
] as const;

const BY_ID = new Map<CurriculumSkillId, CurriculumSkillDefinition>(SKILLS.map((skill) => [skill.id, skill]));

export function listCurriculumSkills(): CurriculumSkillDefinition[] {
  return SKILLS.map((skill) => ({
    ...skill,
    prerequisites: [...skill.prerequisites],
    ...(skill.readingLevels ? { readingLevels: [...skill.readingLevels] } : {}),
    launch: { ...skill.launch },
  }));
}

export function getCurriculumSkill(id: string): CurriculumSkillDefinition | null {
  return BY_ID.get(id as CurriculumSkillId) ?? null;
}

export function isCurriculumSkillId(value: unknown): value is CurriculumSkillId {
  return typeof value === "string" && BY_ID.has(value as CurriculumSkillId);
}

export function curriculumMathSkill(question: MathQuestion): CurriculumSkillId {
  if (question.operation === "comparison") {
    return Math.max(question.left, question.right) <= 20
      ? "math.number_comparison.within_20"
      : "math.number_comparison.within_100";
  }
  if (question.operation === "number_bond") {
    return question.right <= 10 ? "math.number_bonds.to_10" : "math.number_bonds.to_20";
  }
  if (question.operation === "multiplication") {
    const foundation = [2, 5, 10].includes(question.left) || [2, 5, 10].includes(question.right);
    return foundation ? "math.multiplication.tables_2_5_10" : "math.multiplication.tables_2_to_9";
  }
  if (question.operation === "subtraction") {
    return question.left <= 20 ? "math.subtraction.within_20" : "math.subtraction.within_100";
  }
  if (question.answer <= 5) return "math.addition.within_5";
  if (question.answer <= 20) return "math.addition.within_20";
  if (question.answer <= 100) return "math.addition.within_100";
  return "math.addition.within_200";
}

export function curriculumVocabularySkill(exercise: VocabularyExercise, requestedSkill?: string): CurriculumSkillId {
  return classifyGranularLanguageSkill({
    mode: exercise.mode,
    target: exercise.target,
    ...(exercise.emoji ? { emoji: exercise.emoji } : {}),
    ...(exercise.sourceFrench ? { sourceFrench: exercise.sourceFrench } : {}),
    ...(exercise.sourceChinese ? { sourceChinese: exercise.sourceChinese } : {}),
  }, requestedSkill) as CurriculumSkillId;
}

export function curriculumSkillForVocabularyMode(mode: VocabularyMode): CurriculumSkillId {
  if (mode === "copy") return "language.word_build.simple";
  if (mode === "recall") return "language.picture_vocabulary.basic";
  if (mode === "translate") return "language.word_translation.basic";
  if (mode === "sentences") return "language.sentence_patterns.simple";
  return "language.bopomofo.word_build";
}

export function vocabularyModeForCurriculumSkill(id: string): VocabularyMode | null {
  const granular = vocabularyModeForLanguageSkill(id);
  if (granular) return granular;
  const skill = getCurriculumSkill(id);
  return skill?.launch.gameId === "vocab" ? skill.launch.vocabularyMode : null;
}

export function curriculumSkillFitsLearner(skill: CurriculumSkillDefinition, learner: LearnerProfile): boolean {
  if (!skill.directorEligible) return false;
  if (learner.age < skill.minAge) return false;
  if (skill.maxAge != null && learner.age > skill.maxAge) return false;
  if (skill.readingLevels && !skill.readingLevels.includes(learner.readingLevel)) return false;
  return true;
}

export function curriculumSkillsForLearner(learner: LearnerProfile, preferredVocabularyMode?: VocabularyMode): CurriculumSkillDefinition[] {
  const modeRank: Record<VocabularyMode, number> = { copy: 0, recall: 1, translate: 2, sentences: 3, bopomofo: 4 };
  return listCurriculumSkills().filter((skill) => {
    if (!curriculumSkillFitsLearner(skill, learner)) return false;
    if (skill.domain !== "language" || !preferredVocabularyMode) return true;
    const mode = skill.launch.gameId === "vocab" ? skill.launch.vocabularyMode : null;
    if (!mode) return false;
    if (preferredVocabularyMode === "bopomofo") return mode === "bopomofo";
    if (mode === "bopomofo") return false;
    // Word Wizard's selected mode is a ceiling, while all earlier language
    // subskills stay available for warm-up, review and confidence practice.
    return modeRank[mode] <= modeRank[preferredVocabularyMode];
  });
}
